TARGET_CHIP := NRF51822_QFAA_G2
BOARD := BOARD_FLASHBOARD

C_SOURCE_FILES += main.c
C_SOURCE_FILES += nrf_delay.c simple_uart.c 


SDK_PATH = ../../../../
OUTPUT_FILENAME := uart_temp

DEVICE_VARIANT := xxaa
#DEVICE_VARIANT := xxab

#USE_SOFTDEVICE := S110
#USE_SOFTDEVICE := S210

include $(SDK_PATH)Source/templates/gcc/Makefile.common
